// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvService 负责检测 packwiz / Prism Launcher 的装载状态，
 * 并将工具所在目录写入用户级 PATH。
 * 
 * config.toml 是工具路径的唯一持久化来源：无论是用户手动输入
 * 还是程序自动检测到的路径，都会写入 config.toml，方便用户
 * 随时查看与修改。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfigExists 判断全局 config.toml 是否已在磁盘上（首次运行检测，
 * 前端据此决定是否弹出首次引导）。任何一次配置保存都会让文件出现。
 */
export function ConfigExists(): $CancellablePromise<boolean> {
    return $Call.ByID(634800189);
}

/**
 * Configure 将检测到的工具所在目录写入用户级 PATH（幂等），
 * 返回配置后的最新检测结果与实际新增的目录列表（由前端渲染提示文案）
 */
export function Configure(): $CancellablePromise<[$models.ToolInfo[] | null, string[] | null]> {
    return $Call.ByID(4158103609);
}

/**
 * Detect 检测两个工具的装载状态
 */
export function Detect(): $CancellablePromise<$models.ToolInfo[] | null> {
    return $Call.ByID(2098789344);
}

/**
 * GetApiKey 返回已保存的 CurseForge API Key（未配置时为空串）
 */
export function GetApiKey(): $CancellablePromise<string> {
    return $Call.ByID(758417042);
}

/**
 * MarkConfigCreated 立即将当前配置落盘（首次引导完成/跳过后调用），
 * 使下次启动 ConfigExists 返回 true、不再重复引导。
 */
export function MarkConfigCreated(): $CancellablePromise<void> {
    return $Call.ByID(3564884324);
}

/**
 * SetApiKey 保存用户填写的 CurseForge API Key（空串清除）
 */
export function SetApiKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(3983215750, key);
}

/**
 * SetToolPath 保存用户手动指定的工具路径（空串清除），返回最新检测结果
 */
export function SetToolPath(name: string, path: string): $CancellablePromise<$models.ToolInfo[] | null> {
    return $Call.ByID(154116296, name, path);
}
