// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prism$0 from "../prism/models.js";

/**
 * ModVersionResult 是一次批量获取中单个 mod 的结果
 */
export interface ModVersionResult {
    "id": string;
    "name": string;

    /**
     * displayName
     */
    "version": string;
    "ok": boolean;
    "error": string;
}

/**
 * PrismOverview 是 Prism 页面一次性装载所需的全部数据（实例目录 + 实例列表 + 关联视图）。
 * 前端页面装载/刷新时一次调用即可，避免多次往返与重复扫描实例目录。
 */
export interface PrismOverview {
    /**
     * 当前定位到的实例根目录（定位失败时为空）
     */
    "instances_dir": string;

    /**
     * 定位失败的错误码 JSON 文本（空串 = 定位成功）
     */
    "locate_error": string;

    /**
     * 实例列表（定位失败时为空）
     */
    "instances": prism$0.Instance[] | null;

    /**
     * 项目 ↔ 实例关联视图（定位失败时实例侧为失效态）
     */
    "links": prism$0.LinkView[] | null;
}

/**
 * ToolInfo 描述一个工具的检测结果。
 * 不包含用户可见文案：检测来源（Source）由前端按翻译键渲染提示
 */
export interface ToolInfo {
    /**
     * packwiz / prism-launcher
     */
    "name": string;

    /**
     * 是否已安装
     */
    "found": boolean;

    /**
     * 可执行文件或配置目录的完整路径
     */
    "path": string;

    /**
     * 发现来源: config / env / path / default-dir
     */
    "source": string;

    /**
     * 需要加入 PATH 的目录（无可加目录时为空）
     */
    "env_dir": string;

    /**
     * 该目录是否已在用户 PATH 中
     */
    "env_ok": boolean;
}
