// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModVersionResult 是一次批量获取中单个 mod 的结果
 */
export interface ModVersionResult {
    "id": string;
    "name": string;

    /**
     * displayName
     */
    "version": string;
    "ok": boolean;
    "error": string;
}

/**
 * ToolInfo 描述一个工具的检测结果。
 * 不包含用户可见文案：检测来源（Source）由前端按翻译键渲染提示
 */
export interface ToolInfo {
    /**
     * packwiz / prism-launcher
     */
    "name": string;

    /**
     * 是否已安装
     */
    "found": boolean;

    /**
     * 可执行文件或配置目录的完整路径
     */
    "path": string;

    /**
     * 发现来源: config / env / path / default-dir
     */
    "source": string;

    /**
     * 需要加入 PATH 的目录（无可加目录时为空）
     */
    "env_dir": string;

    /**
     * 该目录是否已在用户 PATH 中
     */
    "env_ok": boolean;
}
