// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PrismService 负责 Prism Launcher 实例的定位、扫描与管理。
 * 当前阶段：实例路径检测与实例列表（REQ-3.2）+ 项目关联与一键建链
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prism$0 from "../prism/models.js";

/**
 * AddDirLink 添加目录关联对：项目侧目录名 + 实例侧相对游戏目录路径（默认同名）。
 * 要求项目已关联实例、项目侧目录存在（实例侧目录可稍后由 junction 阶段创建）。
 */
export function AddDirLink(projectName: string, projectDir: string): $CancellablePromise<void> {
    return $Call.ByID(690626371, projectName, projectDir);
}

/**
 * CreateAllLinks 一键关联：将项目根下所有未被 .pgignore 忽略的顶层条目建链。
 * 目录 → junction（实例游戏目录/<name> 指向 项目/<name>）；文件 → 硬链接。
 * mods 目录始终排除（走 meta 推送机制）；实例侧已有真实内容时跳过并报告。
 * 返回逐条目结果，单条目失败不中断其余条目。
 */
export function CreateAllLinks(projectName: string): $CancellablePromise<prism$0.LinkResult[] | null> {
    return $Call.ByID(843673841, projectName);
}

/**
 * CreateInstance 为项目程序创建 Prism 实例（组件取自项目 pack.toml 的版本信息）。
 * 创建成功后可调用 LinkProject 完成关联。
 */
export function CreateInstance(projectName: string): $CancellablePromise<prism$0.Instance> {
    return $Call.ByID(3539630414, projectName);
}

/**
 * EnsurePGIgnore 确保项目存在 .pgignore（已存在不覆盖），返回是否新建。
 * 一键关联前前端据此询问用户是否生成默认忽略规则。
 */
export function EnsurePGIgnore(projectName: string): $CancellablePromise<boolean> {
    return $Call.ByID(1191577420, projectName);
}

/**
 * GetInstancesPath 返回用户手动指定的实例根目录（空串 = 未指定，走自动定位）
 */
export function GetInstancesPath(): $CancellablePromise<string> {
    return $Call.ByID(183525922);
}

/**
 * GetLinks 返回全部项目 ↔ 实例关联的组装视图（读取各项目 packgradle.toml，
 * 实时扫描实例，实例被删时标记失效）
 */
export function GetLinks(): $CancellablePromise<prism$0.LinkView[] | null> {
    return $Call.ByID(1627354796);
}

/**
 * HasPGIgnore 检查项目是否已有 .pgignore 文件（一键关联前询问用）
 */
export function HasPGIgnore(projectName: string): $CancellablePromise<boolean> {
    return $Call.ByID(1444343784, projectName);
}

/**
 * InstancesDir 返回当前定位到的实例根目录（供前端展示与确认）
 */
export function InstancesDir(): $CancellablePromise<string> {
    return $Call.ByID(2516204918);
}

/**
 * LinkProject 关联 packwiz 项目到 Prism 实例（一项目一实例，重复关联覆盖）。
 * 实例须存在于当前实例目录；关联持久化在项目目录下的 packgradle.toml。
 */
export function LinkProject(projectName: string, instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(968070894, projectName, instanceID);
}

/**
 * ListDirLinks 返回某项目的目录关联对（含两侧目录实态）
 */
export function ListDirLinks(projectName: string): $CancellablePromise<prism$0.DirLinkView[] | null> {
    return $Call.ByID(1953249517, projectName);
}

/**
 * ListInstances 返回 Prism 实例列表。
 * 定位链：%APPDATA%\PrismLauncher（配置文件所在）→ prismlauncher.cfg 的 InstanceDir
 * → 扫描实例目录。单个实例解析失败不中断列表（错误落入 Instance.Error），
 * 整体定位失败才返回错误。
 */
export function ListInstances(): $CancellablePromise<prism$0.Instance[] | null> {
    return $Call.ByID(3467682107);
}

/**
 * ListProjectDirs 返回项目根下的顶层目录名（排除 mods 与 .cache），
 * 作为目录同步关联的候选列表
 */
export function ListProjectDirs(projectName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3936976218, projectName);
}

/**
 * RemoveDirLink 移除目录关联对，并删除已建链接（仅链接本身，目标内容不动）
 */
export function RemoveDirLink(projectName: string, projectDir: string): $CancellablePromise<void> {
    return $Call.ByID(2816067440, projectName, projectDir);
}

/**
 * SetInstancesPath 保存用户手动指定的实例根目录（空串清除，恢复自动定位）。
 * 自动定位失败时前端据此引导用户手动输入路径。
 */
export function SetInstancesPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3230208694, path);
}

/**
 * UnlinkProject 解除项目关联（连同其目录关联与已建链接）
 */
export function UnlinkProject(projectName: string): $CancellablePromise<void> {
    return $Call.ByID(3915257647, projectName);
}
