// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PrismService 负责 Prism Launcher 实例的定位、扫描与管理。
 * 当前阶段：实例路径检测与实例列表（REQ-3.2）+ 项目关联与一键建链
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prism$0 from "../prism/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDirLink 添加目录关联对：项目侧目录名 + 实例侧相对游戏目录路径（默认同名）。
 * 要求项目已关联实例、项目侧目录存在（实例侧目录可稍后由 junction 阶段创建）。
 */
export function AddDirLink(projectName: string, projectDir: string): $CancellablePromise<void> {
    return $Call.ByID(690626371, projectName, projectDir);
}

/**
 * CreateAllLinks 一键关联：将项目根下所有未被 .pgignore 忽略的顶层条目建链。
 * 目录 → junction（实例游戏目录/<name> 指向 项目/<name>）；文件 → 硬链接。
 * mods 目录始终排除（走 meta 推送机制）；实例侧已有真实内容时跳过并报告。
 * 返回逐条目结果，单条目失败不中断其余条目。
 */
export function CreateAllLinks(projectName: string): $CancellablePromise<prism$0.LinkResult[] | null> {
    return $Call.ByID(843673841, projectName);
}

/**
 * CreateInstance 为项目程序创建 Prism 实例（组件取自项目 pack.toml 的版本信息）。
 * 创建成功后可调用 LinkProject 完成关联。
 */
export function CreateInstance(projectName: string): $CancellablePromise<prism$0.Instance> {
    return $Call.ByID(3539630414, projectName);
}

/**
 * EnsurePGIgnore 确保项目存在 .pgignore（已存在不覆盖），返回是否新建。
 * 一键关联前前端据此询问用户是否生成默认忽略规则。
 */
export function EnsurePGIgnore(projectName: string): $CancellablePromise<boolean> {
    return $Call.ByID(1191577420, projectName);
}

/**
 * GetInstancesPath 返回用户手动指定的实例根目录（空串 = 未指定，走自动定位）
 */
export function GetInstancesPath(): $CancellablePromise<string> {
    return $Call.ByID(183525922);
}

/**
 * GetLinks 返回全部项目 ↔ 实例关联的组装视图（读取各项目 packgradle.toml，
 * 实时扫描实例，实例被删时标记失效）
 */
export function GetLinks(): $CancellablePromise<prism$0.LinkView[] | null> {
    return $Call.ByID(1627354796);
}

/**
 * HasPGIgnore 检查项目是否已有 .pgignore 文件（一键关联前询问用）
 */
export function HasPGIgnore(projectName: string): $CancellablePromise<boolean> {
    return $Call.ByID(1444343784, projectName);
}

/**
 * InstancesDir 返回当前定位到的实例根目录（供前端展示与确认）
 */
export function InstancesDir(): $CancellablePromise<string> {
    return $Call.ByID(2516204918);
}

/**
 * LinkProject 关联 packwiz 项目到 Prism 实例（一项目一实例，重复关联覆盖）。
 * 实例须存在于当前实例目录；关联持久化在项目目录下的 packgradle.toml。
 * 若项目已关联其他实例，先清理旧实例侧已建链接，避免残留孤儿 junction/硬链接。
 */
export function LinkProject(projectName: string, instanceID: string): $CancellablePromise<void> {
    return $Call.ByID(968070894, projectName, instanceID);
}

/**
 * ListDirFiles 递归列出项目目录下的全部文件（相对 projectDir，排除隐藏项），
 * 供文件级同步的勾选界面使用
 */
export function ListDirFiles(projectName: string, dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1654091995, projectName, dir);
}

/**
 * ListDirLinks 返回某项目的目录关联对（含两侧目录实态）
 */
export function ListDirLinks(projectName: string): $CancellablePromise<prism$0.DirLinkView[] | null> {
    return $Call.ByID(1953249517, projectName);
}

/**
 * ListInstanceDirFiles 递归列出实例侧游戏目录 <dir> 下的文件（相对 dir，排除隐藏项），
 * 供文件级同步从目标侧选择要纳入同步的文件。
 * 实例侧目录是 junction（整目录模式）时返回空列表——此时两侧为同一物理目录，无需选择；
 * files 模式且实例侧目录不存在时（刚由 junction 切换过来），回退列出项目侧文件——
 * 切换前两侧本就是同一物理目录，清单等价，保证“选择同步文件”流程可用。
 */
export function ListInstanceDirFiles(projectName: string, dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2111168812, projectName, dir);
}

/**
 * ListInstances 返回 Prism 实例列表。
 * 定位链：%APPDATA%\PrismLauncher（配置文件所在）→ prismlauncher.cfg 的 InstanceDir
 * → 扫描实例目录。单个实例解析失败不中断列表（错误落入 Instance.Error），
 * 整体定位失败才返回错误。
 */
export function ListInstances(): $CancellablePromise<prism$0.Instance[] | null> {
    return $Call.ByID(3467682107);
}

/**
 * ListProjectDirs 返回项目根下的顶层目录名（排除 mods 与 .cache），
 * 作为目录同步关联的候选列表
 */
export function ListProjectDirs(projectName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3936976218, projectName);
}

/**
 * ManualLinkDir 手动链接单个目录（前端二次确认后调用）：
 *   - 实例侧已是 junction 指向项目侧 → existing（幂等）
 *   - 实例侧为空目录 → 直接删除后建链
 *   - 实例侧非空 → 先将内容复制到项目目录（同名文件跳过，项目侧权威），
 *     再删除实例侧目录建立 junction
 *   - 实例侧不存在 → 直接建链
 */
export function ManualLinkDir(projectName: string, dir: string): $CancellablePromise<prism$0.LinkResult> {
    return $Call.ByID(535050274, projectName, dir);
}

/**
 * MetaDiff 计算项目 ↔ 实例 mods 的元数据差异并刷新缓存：
 * 项目侧以 index.toml 权威列表为准，实例侧扫描 mods/.index 的 pw.toml。
 * 每次「查看差异」时调用（重新计算 + 写入 .cache/metadiff.cache），
 * 不做实时监听，避免目录变化带来的性能开销。
 */
export function MetaDiff(projectName: string): $CancellablePromise<prism$0.MetaDiff> {
    return $Call.ByID(3469852635, projectName);
}

/**
 * Overview 一次性返回 Prism 页所需的全部数据。
 * 定位失败不中断：错误落入 LocateError（前端解析错误码渲染引导），关联视图仍可用。
 */
export function Overview(): $CancellablePromise<$models.PrismOverview> {
    return $Call.ByID(2790614566);
}

/**
 * PullMeta 将实例 mods/.index 的元数据拉回项目 mods 目录（packwiz 格式）：
 * 删除 x-prismlauncher-* 扩展字段与 [download] 表中的 url 条目。
 * modID 非空时仅拉取该 mod（空串拉取全部）。拉回后需运行 packwiz refresh 收录。
 */
export function PullMeta(projectName: string, modID: string): $CancellablePromise<number> {
    return $Call.ByID(655690463, projectName, modID);
}

/**
 * PushMeta 将项目 mod 元数据推送到实例 mods/.index（Prism 兼容格式）：
 * 每个 mod 的 pw.toml 在 side 条目后插入 x-prismlauncher-* 四个扩展字段
 * （loaders/mc-versions/release-type/version-number），供 Prism 识别。
 * modID 非空时仅推送该 mod（空串推送全部）。mods 目录本身不建 junction（meta 推送机制）。
 */
export function PushMeta(projectName: string, modID: string): $CancellablePromise<number> {
    return $Call.ByID(3796457884, projectName, modID);
}

/**
 * RemoveDirLink 移除目录关联对，并删除已建链接（仅链接本身，目标内容不动）。
 * 实例目录无法定位时返回错误并保留配置，避免静默留下无法清理的孤儿链接。
 */
export function RemoveDirLink(projectName: string, projectDir: string): $CancellablePromise<void> {
    return $Call.ByID(2816067440, projectName, projectDir);
}

/**
 * SelectInstanceFiles 将实例侧选中的文件纳入文件级同步：
 *  1. 实例侧文件移动到项目目录（成为项目权威内容；项目侧已有同名文件时跳过不覆盖）；
 *     若文件已在项目侧（例如刚由整目录 junction 切换为文件级同步），跳过移动直接建链；
 *  2. 移动后从项目目录建硬链接回实例侧（同步生效）；链接失败时回滚移动；
 *  3. 仅把真正建链成功的文件记录到清单（mode=files），失败项不写清单。
 * 
 * 实例侧目录为 junction（整目录模式）时拒绝——需先切换为文件级同步。
 */
export function SelectInstanceFiles(projectName: string, dir: string, files: string[] | null): $CancellablePromise<prism$0.LinkResult[] | null> {
    return $Call.ByID(3318395977, projectName, dir, files);
}

/**
 * SetDirLinkFiles 设置文件级同步的清单（自动切换为 files 模式并重建链接）。
 * 清单为空时视为退出文件级模式（回到 junction）。
 */
export function SetDirLinkFiles(projectName: string, dir: string, files: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3091833297, projectName, dir, files);
}

/**
 * SetDirLinkMode 切换目录关联的同步模式（""=整目录 junction / "files"=文件级）。
 * 切换时自动重建链接：清理旧模式链接，按新模式建链；
 * 切回 junction 且实例侧已有内容时返回错误提示先手动处理。
 */
export function SetDirLinkMode(projectName: string, dir: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3471433285, projectName, dir, mode);
}

/**
 * SetInstancesPath 保存用户手动指定的实例根目录（空串清除，恢复自动定位）。
 * 自动定位失败时前端据此引导用户手动输入路径。
 */
export function SetInstancesPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3230208694, path);
}

/**
 * UnlinkProject 解除项目关联（连同其目录关联与已建链接）
 */
export function UnlinkProject(projectName: string): $CancellablePromise<void> {
    return $Call.ByID(3915257647, projectName);
}
