// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirLinkView 是目录关联对的视图（含两侧目录实态与同步模式）
 */
export interface DirLinkView {
    "project": string;
    "instance": string;

    /**
     * 项目根下目录名
     */
    "project_dir": string;

    /**
     * 实例游戏目录下相对路径
     */
    "instance_dir": string;

    /**
     * ""=整目录 junction / "files"=文件级同步
     */
    "mode": string;

    /**
     * files 模式的同步文件清单（相对 ProjectDir）
     */
    "files": string[] | null;

    /**
     * 项目侧目录是否存在
     */
    "project_exists": boolean;

    /**
     * 实例侧目录是否存在
     */
    "instance_exists": boolean;
}

/**
 * Instance 描述一个从 Prism Launcher 实例目录扫描到的实例。
 * 解析失败时不中断列表，错误码 JSON 文本落入 Error 字段（同 PackProject.Error 容错哲学）
 */
export interface Instance {
    /**
     * 实例 ID = instances/ 下的文件夹名
     */
    "id": string;

    /**
     * instance.cfg 的 name= 显示名，缺失时回退 ID
     */
    "name": string;

    /**
     * 实例目录完整路径
     */
    "path": string;

    /**
     * 游戏目录（<实例>/minecraft，可能尚不存在）
     */
    "game_dir": string;

    /**
     * instgroups.json 分组（无分组为空串）
     */
    "group": string;

    /**
     * mmc-pack.json 中 net.minecraft 组件版本
     */
    "minecraft": string;

    /**
     * fabric / forge / neoforge / quilt / liteloader / ""
     */
    "modloader": string;

    /**
     * 加载器组件版本
     */
    "modloader_version": string;

    /**
     * 解析失败原因（errs JSON 文本）
     */
    "error": string;
}

/**
 * LinkResult 是一键关联中单个条目的建链结果
 */
export interface LinkResult {
    /**
     * 相对项目根的条目名
     */
    "name": string;

    /**
     * 目录（junction）/ 文件（硬链接）
     */
    "is_dir": boolean;

    /**
     * linked / existing / skipped / manual / error
     */
    "status": string;

    /**
     * 跳过原因或错误文本
     */
    "detail": string;
}

/**
 * LinkView 是「项目 ↔ 实例」关联的组装视图（服务层实时扫描实例组装，前端渲染）
 */
export interface LinkView {
    "project": string;
    "project_path": string;
    "instance_id": string;

    /**
     * 实时扫描获取；实例被删/改名时为空
     */
    "instance_name": string;
    "instance_path": string;

    /**
     * 实例当前是否仍可解析
     */
    "instance_valid": boolean;
}

/**
 * MetaDiff 是项目 ↔ 实例 mods 元数据的差异（按 index.toml 权威列表 vs 实例 mods/.index 对比）。
 * 持久化到 <项目目录>/.cache/metadiff.cache：每次「查看差异」时重新计算并刷新缓存，
 * 避免实时监听目录变化带来的性能开销。
 */
export interface MetaDiff {
    /**
     * 计算时间（RFC3339）
     */
    "fetched_at": string;

    /**
     * 实例 .index 有、项目 index.toml 无（可拉取）
     */
    "instance_only": string[] | null;

    /**
     * 项目有、实例 .index 无（可推送）
     */
    "project_only": string[] | null;

    /**
     * 双端版本不一致
     */
    "version_diff": VersionDiffItem[] | null;
}

/**
 * VersionDiffItem 是双端版本不一致的单个 mod
 */
export interface VersionDiffItem {
    "id": string;

    /**
     * 项目侧版本（packwiz 元数据）
     */
    "project_version": string;

    /**
     * 实例侧版本（.index 元数据）
     */
    "instance_version": string;
}
