// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DirLinkView 是目录关联对的视图（含两侧目录实态，junction 状态由 Phase 3 补充）
 */
export interface DirLinkView {
    "project": string;
    "instance": string;

    /**
     * 项目根下目录名
     */
    "project_dir": string;

    /**
     * 实例游戏目录下相对路径
     */
    "instance_dir": string;

    /**
     * 项目侧目录是否存在
     */
    "project_exists": boolean;

    /**
     * 实例侧目录是否存在
     */
    "instance_exists": boolean;
}

/**
 * Instance 描述一个从 Prism Launcher 实例目录扫描到的实例。
 * 解析失败时不中断列表，错误码 JSON 文本落入 Error 字段（同 PackProject.Error 容错哲学）
 */
export interface Instance {
    /**
     * 实例 ID = instances/ 下的文件夹名
     */
    "id": string;

    /**
     * instance.cfg 的 name= 显示名，缺失时回退 ID
     */
    "name": string;

    /**
     * 实例目录完整路径
     */
    "path": string;

    /**
     * 游戏目录（<实例>/minecraft，可能尚不存在）
     */
    "game_dir": string;

    /**
     * instgroups.json 分组（无分组为空串）
     */
    "group": string;

    /**
     * mmc-pack.json 中 net.minecraft 组件版本
     */
    "minecraft": string;

    /**
     * fabric / forge / neoforge / quilt / liteloader / ""
     */
    "modloader": string;

    /**
     * 加载器组件版本
     */
    "modloader_version": string;

    /**
     * 解析失败原因（errs JSON 文本）
     */
    "error": string;
}

/**
 * LinkResult 是一键关联中单个条目的建链结果
 */
export interface LinkResult {
    /**
     * 相对项目根的条目名
     */
    "name": string;

    /**
     * 目录（junction）/ 文件（硬链接）
     */
    "is_dir": boolean;

    /**
     * linked / existing / skipped / manual / error
     */
    "status": string;

    /**
     * 跳过原因或错误文本
     */
    "detail": string;
}

/**
 * LinkView 是「项目 ↔ 实例」关联的组装视图（服务层实时扫描实例组装，前端渲染）
 */
export interface LinkView {
    "project": string;
    "project_path": string;
    "instance_id": string;

    /**
     * 实时扫描获取；实例被删/改名时为空
     */
    "instance_name": string;
    "instance_path": string;

    /**
     * 实例当前是否仍可解析
     */
    "instance_valid": boolean;
}
