// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as model$0 from "../../../../../packgradle/internal/core/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as prism$0 from "../../../../../packgradle/internal/prism/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "packgradle://event": model$0.EventEnvelope;
            "packgradle:mods-diff": prism$0.ModsWatchEvent;
        }
    }
}
