// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConfirmationRequirementDTO {
    "code": string;
    "severity": string;
    "resource_count": number;
}

export interface ConflictDTO {
    "resource_id": string;
    "kind": string;
    "base"?: RepresentationDTO | null;
    "project"?: RepresentationDTO | null;
    "runtime"?: RepresentationDTO | null;
    "detail"?: string;
}

export interface ContentRefDTO {
    "algorithm": string;
    "digest": string;
    "size": number;
}

/**
 * DiagnosticDTO 是扫描/映射诊断投影（含 diag.mapping.collision 碰撞证据；
 * code 的文案由前端 locale 提供）。
 */
export interface DiagnosticDTO {
    "severity": string;
    "code": string;
    "args": string[] | null;
    "detail"?: string;
    "resource_id"?: string;
    "relative_path"?: string;
}

/**
 * EndpointDTO 是端点投影。
 */
export interface EndpointDTO {
    "id": string;
    "adapter": string;
    "display_name": string;
    "root_path": string;
    "adapter_identity"?: string;
    "binding_fingerprint": string;

    /**
     * InstanceDir 仅 runtime 侧填充：实例目录（PrepareRelation 输入 root_path
     * 的取值来源），由游戏目录父目录派生；project 侧为空。
     */
    "instance_dir"?: string;
}

/**
 * EndpointHealthDTO 是端点健康检查结果（只读；status: ok|missing|identity_mismatch）。
 */
export interface EndpointHealthDTO {
    "endpoint_id": string;
    "status": string;
    "path_exists": boolean;
    "fingerprint_matches": boolean;
    "checked_at": string;
}

export interface MappingRuleDTO {
    "id": string;
    "resource_kind": string;
    "project_prefix": string;
    "runtime_prefix": string;
    "include": string[] | null;
    "exclude": string[] | null;
    "direction": string;
    "materialization": string;
    "merge_policy": string;
    "runtime_local": string;
}

export interface OperationDTO {
    "id": string;
    "kind": string;
    "resource_id": string;
    "preconditions": PreconditionDTO[] | null;
    "reversible": boolean;
}

export interface PlanSummaryDTO {
    "resource_total": number;
    "adopt_equal_count": number;
    "create_count": number;
    "modify_count": number;
    "delete_count": number;
    "conflict_count": number;
}

/**
 * PolicyDTO / MappingRuleDTO 是策略投影。
 */
export interface PolicyDTO {
    "schema_version": number;
    "policy_id": string;
    "revision": number;
    "rules": MappingRuleDTO[] | null;
}

/**
 * PreconditionDTO / OperationDTO 是计划操作投影。
 */
export interface PreconditionDTO {
    "resource_id": string;
    "side": string;
    "expected"?: ContentRefDTO | null;
    "existence": string;
}

/**
 * PreparationCheckDTO 是预检单项。
 */
export interface PreparationCheckDTO {
    "code": string;
    "passed": boolean;
    "severity": string;
    "args": string[] | null;
    "detail": string;
}

/**
 * PrepareRelationDTO 是 PrepareRelation 输入。
 */
export interface PrepareRelationDTO {
    "project_root": string;
    "runtime_instance_dir": string;
    "policy_set": string;

    /**
     * 勾选的建议规则 ID（默认不勾选，确认前不写受管）
     */
    "suggestions"?: string[] | null;
}

/**
 * PrepareSyncDTO 是 PrepareSync 输入。
 */
export interface PrepareSyncDTO {
    "relation_id": string;
    "relation_revision": number;
    "input_project_snapshot_id": string;
    "input_runtime_snapshot_id": string;
    "requested_exactness": string;
}

/**
 * ProblemDTO 是结构化错误（code/args/detail；文案由前端 locale 提供）。
 */
export interface ProblemDTO {
    "code": string;
    "args": string[] | null;
    "detail": string;
}

/**
 * ProjectCandidateDTO 是项目源发现候选（registered 按 binding fingerprint 幂等判定）。
 */
export interface ProjectCandidateDTO {
    "display_name": string;
    "root_path": string;
    "pack_toml_path": string;
    "minecraft"?: string;
    "modloader"?: string;
    "registered": boolean;
    "endpoint_id"?: string;
}

/**
 * RegisterEndpointDTO 是端点登记输入（契约 03 §2.5；project: pack.toml 所在目录，
 * runtime: Prism 实例目录）。
 */
export interface RegisterEndpointDTO {
    "root_path": string;
}

/**
 * RelationDTO 是关系投影。
 */
export interface RelationDTO {
    "schema_version": number;
    "relation_id": string;
    "project": EndpointDTO;
    "runtime": EndpointDTO;
    "policy_set": string;
    "revision": number;
    "health": string;
    "created_at": string;
}

/**
 * RelationPreparationDTO 是 PrepareRelation 结果。
 */
export interface RelationPreparationDTO {
    "schema_version": number;
    "preparation_id": string;
    "created_at": string;
    "expires_at": string;
    "checks": PreparationCheckDTO[] | null;
    "project"?: EndpointDTO | null;
    "runtime"?: EndpointDTO | null;
    "policy": PolicyDTO;
}

/**
 * RepresentationDTO 是冲突证据中的表示。
 */
export interface RepresentationDTO {
    "relative_path": string;
    "format": string;
    "content"?: ContentRefDTO | null;
}

/**
 * ResolutionDTO 是单个冲突选择。
 */
export interface ResolutionDTO {
    "resource_id": string;
    "choice": string;
}

/**
 * ResolvePlanDTO 是 ResolvePlan 输入。
 */
export interface ResolvePlanDTO {
    "plan_id": string;
    "resolutions": ResolutionDTO[] | null;
}

/**
 * RuntimeCandidateDTO 是运行实例发现候选（registered 按 adapter identity 幂等判定）。
 */
export interface RuntimeCandidateDTO {
    "instance_id": string;
    "instance_dir": string;
    "display_name": string;
    "game_dir": string;
    "minecraft"?: string;
    "modloader"?: string;
    "registered": boolean;
    "endpoint_id"?: string;
}

/**
 * SnapshotSummaryDTO 是快照摘要。
 */
export interface SnapshotSummaryDTO {
    "snapshot_id": string;
    "side": string;
    "captured_at": string;
    "snapshot_digest": string;
    "resource_count": number;
}

/**
 * SyncPlanDTO 是计划投影（Status 反映读取时计算的 stale/expired）。
 */
export interface SyncPlanDTO {
    "schema_version": number;
    "plan_id": string;
    "relation_id": string;
    "kind": string;
    "resolved_from_plan_id"?: string;
    "base_baseline_id"?: string;
    "base_baseline_digest"?: string;
    "input_project_snapshot_id": string;
    "input_runtime_snapshot_id": string;
    "input_project_snapshot_digest": string;
    "input_runtime_snapshot_digest": string;
    "relation_revision": number;
    "policy_digest": string;
    "expected_bindings": { [_ in string]?: string } | null;
    "plan_digest": string;
    "status": string;
    "expires_at": string;
    "operations": OperationDTO[] | null;
    "conflicts": ConflictDTO[] | null;
    "resolutions": ResolutionDTO[] | null;
    "confirmation_requirements": ConfirmationRequirementDTO[] | null;
    "summary": PlanSummaryDTO;
    "diagnostics": DiagnosticDTO[] | null;
}

/**
 * TaskDTO 是任务投影。
 */
export interface TaskDTO {
    "schema_version": number;
    "task_id": string;
    "relation_id"?: string;
    "task_sequence": number;
    "kind": string;
    "status": string;
    "outcome"?: string;
    "phase": string;
    "completed": number;
    "total": number;
    "message_key": string;
    "message_args": string[] | null;
    "plan_id"?: string;
    "commit_id"?: string;
    "can_cancel": boolean;
    "created_at": string;
    "updated_at": string;
    "problem"?: ProblemDTO | null;
}

/**
 * TaskPageDTO 是任务分页。
 */
export interface TaskPageDTO {
    "schema_version": number;
    "items": TaskDTO[] | null;
    "next_cursor"?: string;
}

/**
 * WorkspaceDTO 是工作区详情。
 */
export interface WorkspaceDTO {
    "schema_version": number;
    "relation": RelationDTO;
    "state": WorkspaceStateDTO;
    "latest_project_snapshot"?: SnapshotSummaryDTO | null;
    "latest_runtime_snapshot"?: SnapshotSummaryDTO | null;
}

/**
 * WorkspacePageDTO 是工作区分页。
 */
export interface WorkspacePageDTO {
    "schema_version": number;
    "items": WorkspaceDTO[] | null;
    "next_cursor"?: string;
}

/**
 * WorkspaceStateDTO 是工作区正交状态（架构 §10.5）。
 */
export interface WorkspaceStateDTO {
    "scan_state": string;
    "baseline_state": string;
    "diff_state": string;
    "relation_health": string;
    "active_task_id"?: string;
    "relation_revision": number;
}
