// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionAvailabilityDTO 是单动作可用性，由后端按当前状态推导（架构 §10.4）。
 * 前端不得自行推断；不可用动作必须带原因码供 locale 渲染。
 */
export interface ActionAvailabilityDTO {
    /**
     * scan|prepare_sync|apply_sync|quick_update|prepare_restore|apply_restore|rebind
     */
    "action": string;
    "available": boolean;
    "reason_code"?: string;
    "reason_args"?: string[] | null;
}

/**
 * ApplyOperationDTO 是单操作行投影。硬约束 4：不含 temp_relative_path / ownership_proof_json。
 */
export interface ApplyOperationDTO {
    "operation_id": string;
    "ordinal": number;

    /**
     * pending|running|applied|verified|failed|compensated（ADR-0004 §2 单调路径）
     */
    "status": string;
    "resource_id"?: string;

    /**
     * root-relative，非临时路径
     */
    "relative_path"?: string;

    /**
     * 与计划操作一致（create/modify/delete）
     */
    "change_kind"?: string;

    /**
     * 终局摘要码（成功为空；失败/补偿带说明码）
     */
    "result_code"?: string;
}

/**
 * ApplyOperationPageDTO 是逐操作清单分页（ordinal 升序；cursor=上一页末条 operation_id）。
 */
export interface ApplyOperationPageDTO {
    "schema_version": number;
    "items": ApplyOperationDTO[] | null;
    "next_cursor"?: string;
}

/**
 * ApplyRunDTO 是一次 Apply 的运行头投影（ADR-0004 §1 六阶段；契约 05 §3.2）。
 */
export interface ApplyRunDTO {
    "schema_version": number;

    /**
     * 即 run_id（apply_runs 主键）
     */
    "task_id": string;
    "relation_id": string;
    "plan_id": string;
    "plan_digest": string;

    /**
     * prepared|staged|applying|verifying|committed|recovery_required
     */
    "state": string;
    "operation_count": number;
    "staging_cleared": boolean;

    /**
     * 人工确认时间（recovery_required 收口后）
     */
    "acknowledged_at"?: string;

    /**
     * committed 后回填
     */
    "commit_id"?: string;
    "created_at": string;
    "updated_at": string;
}

/**
 * ChangeDTO 是单资源三态 Diff 行。Base 在无基线时缺省。
 */
export interface ChangeDTO {
    "resource_id": string;
    "resource_kind": string;
    "relative_path": string;
    "classification": string;
    "base"?: RepresentationDTO | null;
    "project"?: RepresentationDTO | null;
    "runtime"?: RepresentationDTO | null;
    "conflicts": ConflictDTO[] | null;
    "diagnostics": DiagnosticDTO[] | null;
}

/**
 * ChangesPageDTO 是资源级 Diff 分页。
 */
export interface ChangesPageDTO {
    "schema_version": number;
    "items": ChangeDTO[] | null;
    "summary": ChangesSummaryDTO;
    "next_cursor"?: string;
}

/**
 * ChangesSummaryDTO 是全量分组计数（不受筛选影响），供筛选条与页脚展示。
 */
export interface ChangesSummaryDTO {
    "total": number;
    "noop_count": number;
    "converged_count": number;
    "adopt_equal_count": number;
    "init_choice_count": number;
    "create_count": number;
    "modify_count": number;
    "delete_count": number;
    "conflict_count": number;
}

/**
 * CommitChangeDTO 是单资源变更行（源：commit_changes；before/after 为联表表示摘要，缺省 null）。
 */
export interface CommitChangeDTO {
    "resource_id": string;
    "change_kind": string;

    /**
     * 表示摘要（联表），缺省 null
     */
    "project_before"?: string | null;
    "project_after"?: string | null;
    "runtime_before"?: string | null;
    "runtime_after"?: string | null;
}

/**
 * CommitDTO 是单提交详情（changes 全量，单 commit 不分页）。
 */
export interface CommitDTO {
    "schema_version": number;
    "summary": CommitSummaryDTO;
    "plan_id": string;
    "changes": CommitChangeDTO[] | null;

    /**
     * Skipped 是本场剔出的取数失败清单（契约 06 §3.7/ADR-0008 §7，票 #63）：
     * 成功 N + 跳过 M（带 err.download.* 原因码）；旧行无该记录为空数组。
     */
    "skipped": CommitSkippedDTO[] | null;
}

/**
 * CommitPageDTO 是历史列表分页（created_at DESC；cursor=上一页末条 commit_id）。
 */
export interface CommitPageDTO {
    "schema_version": number;
    "items": CommitSummaryDTO[] | null;
    "next_cursor"?: string;

    /**
     * PrunedBeforeCount 是墓碑计数（契约 06 §3.8，票 #64）；N=0 前端不渲染。
     */
    "pruned_before_count": number;
}

/**
 * CommitSkippedDTO 是跳过清单单行：资源 ID + 原因码（文案由前端 locale 提供）。
 */
export interface CommitSkippedDTO {
    "resource_id": string;
    "reason_code": string;
    "reason_args"?: string[] | null;
}

/**
 * CommitSummaryDTO 是历史列表行。
 */
export interface CommitSummaryDTO {
    "commit_id": string;

    /**
     * initialize|sync|restore
     */
    "kind": string;

    /**
     * exact|partial
     */
    "completeness": string;
    "remaining_change_count": number;
    "created_at": string;
}

/**
 * ConfirmPlanDTO 是计划确认输入（契约 05 §3.1）。成功返回 TaskDTO
 * （kind=apply，status=queued，PlanID 字段回填）；幂等重入返回既有任务。
 */
export interface ConfirmPlanDTO {
    "plan_id": string;
}

/**
 * ConfirmRestorePlanDTO 是回滚确认输入（契约 06 §3.4；票 #60）。成功返回
 * TaskDTO（kind=restore，status=queued，PlanID 字段回填）；幂等重入返回既有
 * 任务；failed 终局重入建新运行；committed 后 err.plan.apply_not_reentrant。
 */
export interface ConfirmRestorePlanDTO {
    "plan_id": string;
}

export interface ConfirmationRequirementDTO {
    "code": string;
    "severity": string;
    "resource_count": number;
}

export interface ConflictDTO {
    "resource_id": string;
    "kind": string;
    "base"?: RepresentationDTO | null;
    "project"?: RepresentationDTO | null;
    "runtime"?: RepresentationDTO | null;
    "detail"?: string;
}

export interface ContentRefDTO {
    "algorithm": string;
    "digest": string;
    "size": number;
}

/**
 * DiagnosticDTO 是扫描/映射诊断投影（含 diag.mapping.collision 碰撞证据；
 * code 的文案由前端 locale 提供）。
 */
export interface DiagnosticDTO {
    "severity": string;
    "code": string;
    "args": string[] | null;
    "detail"?: string;
    "resource_id"?: string;
    "relative_path"?: string;
}

/**
 * EndpointDTO 是端点投影。
 */
export interface EndpointDTO {
    "id": string;
    "adapter": string;
    "display_name": string;
    "root_path": string;
    "adapter_identity"?: string;
    "binding_fingerprint": string;

    /**
     * InstanceDir 仅 runtime 侧填充：实例目录（PrepareRelation 输入 root_path
     * 的取值来源），由游戏目录父目录派生；project 侧为空。
     */
    "instance_dir"?: string;
}

/**
 * EndpointHealthDTO 是端点健康检查结果（只读；status: ok|missing|identity_mismatch）。
 */
export interface EndpointHealthDTO {
    "endpoint_id": string;
    "status": string;
    "path_exists": boolean;
    "fingerprint_matches": boolean;
    "checked_at": string;
}

/**
 * GetChangesDTO 是资源级 Changes 查询输入（契约 03 §2.2；读时计算，快照对缺省
 * 取两侧最新）。分页按 resource_id 字节序，cursor 为上一页最后一条 resource_id。
 */
export interface GetChangesDTO {
    "relation_id": string;
    "project_snapshot_id"?: string;
    "runtime_snapshot_id"?: string;

    /**
     * diff 分类单值筛选
     */
    "classification"?: string;

    /**
     * mod|text_file|binary_file
     */
    "resource_kind"?: string;

    /**
     * root-relative 路径前缀
     */
    "path_prefix"?: string;
    "cursor"?: string;
    "limit": number;
}

/**
 * HashCacheStatsDTO 是 hash cache 命中统计（进程生命周期累计；
 * 热扫描命中证明与 T14 性能基线供数）。
 */
export interface HashCacheStatsDTO {
    "schema_version": number;
    "hits": number;
    "misses": number;
    "hit_ratio": number;
}

export interface MappingRuleDTO {
    "id": string;
    "resource_kind": string;
    "project_prefix": string;
    "runtime_prefix": string;
    "include": string[] | null;
    "exclude": string[] | null;
    "direction": string;
    "materialization": string;
    "merge_policy": string;
    "runtime_local": string;
}

export interface OperationDTO {
    "id": string;
    "kind": string;
    "resource_id": string;
    "preconditions": PreconditionDTO[] | null;
    "reversible": boolean;

    /**
     * Materialization 是物化模式（契约 06 §3.7，票 #63）：copy|download，由
     * 后端推导（有重取信息的 mod 写操作 → download，其余 → copy）；旧行空值
     * ＝copy 兼容。
     */
    "materialization"?: string;

    /**
     * PreserveSkip 是「旧版本不留存」警示行标记（契约 06 §3.7；ADR-0007 §7，
     * 票 #64）：非 mod 单文件超过 preserve_max_bytes，不做 before 保全。
     * 只增不删，同「不可重取」警示先例（deletion_warn）。
     */
    "preserve_skip"?: boolean;
}

export interface PlanSummaryDTO {
    "resource_total": number;
    "adopt_equal_count": number;
    "create_count": number;
    "modify_count": number;
    "delete_count": number;
    "conflict_count": number;
}

/**
 * PolicyDTO / MappingRuleDTO 是策略投影。
 */
export interface PolicyDTO {
    "schema_version": number;
    "policy_id": string;
    "revision": number;
    "rules": MappingRuleDTO[] | null;

    /**
     * RelationRevision 是关系级策略代次（ADR-0002 决议 5：与模板版本语义独立、
     * 互不驱动）。仅 Mapping 读写投影填充（mappings 页乐观锁 expected_revision
     * 的取值来源），预检投影恒 0；任何修订号不进入用户可见文案（决议 3）。
     */
    "relation_revision"?: number;
}

/**
 * PreconditionDTO / OperationDTO 是计划操作投影。
 */
export interface PreconditionDTO {
    "resource_id": string;
    "side": string;
    "expected"?: ContentRefDTO | null;
    "existence": string;
}

/**
 * PreparationCheckDTO 是预检单项。
 */
export interface PreparationCheckDTO {
    "code": string;
    "passed": boolean;
    "severity": string;
    "args": string[] | null;
    "detail": string;
}

/**
 * PrepareRebindDTO 是重绑预检输入（契约 03 §2.4；一次只重绑一侧）。
 */
export interface PrepareRebindDTO {
    "relation_id": string;

    /**
     * project|runtime
     */
    "side": string;

    /**
     * 新端点根路径（project: pack.toml 所在目录；runtime: Prism 实例目录）
     */
    "root_path": string;
}

/**
 * PrepareRelationDTO 是 PrepareRelation 输入。
 */
export interface PrepareRelationDTO {
    "project_root": string;
    "runtime_instance_dir": string;
    "policy_set": string;

    /**
     * 勾选的建议规则 ID（默认不勾选，确认前不写受管）
     */
    "suggestions"?: string[] | null;
}

/**
 * PrepareSyncDTO 是 PrepareSync 输入。
 */
export interface PrepareSyncDTO {
    "relation_id": string;
    "relation_revision": number;
    "input_project_snapshot_id": string;
    "input_runtime_snapshot_id": string;
    "requested_exactness": string;
}

/**
 * ProblemDTO 是结构化错误（code/args/detail；文案由前端 locale 提供）。
 */
export interface ProblemDTO {
    "code": string;
    "args": string[] | null;
    "detail": string;
}

/**
 * ProjectCandidateDTO 是项目源发现候选（registered 按 binding fingerprint 幂等判定）。
 */
export interface ProjectCandidateDTO {
    "display_name": string;
    "root_path": string;
    "pack_toml_path": string;
    "minecraft"?: string;
    "modloader"?: string;
    "registered": boolean;
    "endpoint_id"?: string;
}

/**
 * RebindPreparationDTO 是 PrepareRebind 结果（契约 03 §2.4）。new_endpoint 与
 * old_endpoint 共享同一端点 ID：ApplyRebind 原位更新该端点行的绑定。
 */
export interface RebindPreparationDTO {
    "schema_version": number;
    "preparation_id": string;
    "created_at": string;
    "expires_at": string;
    "side": string;
    "checks": PreparationCheckDTO[] | null;
    "old_endpoint": EndpointDTO;
    "new_endpoint": EndpointDTO;
    "fingerprint_changed": boolean;

    /**
     * inherit|reinitialize
     */
    "baseline_inheritance": string;
    "invalidated_plan_count": number;
}

/**
 * RegisterEndpointDTO 是端点登记输入（契约 03 §2.5；project: pack.toml 所在目录，
 * runtime: Prism 实例目录）。
 */
export interface RegisterEndpointDTO {
    "root_path": string;
}

/**
 * RelationDTO 是关系投影。
 */
export interface RelationDTO {
    "schema_version": number;
    "relation_id": string;
    "project": EndpointDTO;
    "runtime": EndpointDTO;
    "policy_set": string;
    "revision": number;
    "health": string;
    "created_at": string;
}

/**
 * RelationPreparationDTO 是 PrepareRelation 结果。
 */
export interface RelationPreparationDTO {
    "schema_version": number;
    "preparation_id": string;
    "created_at": string;
    "expires_at": string;
    "checks": PreparationCheckDTO[] | null;
    "project"?: EndpointDTO | null;
    "runtime"?: EndpointDTO | null;
    "policy": PolicyDTO;
}

/**
 * RepresentationDTO 是冲突证据中的表示。
 */
export interface RepresentationDTO {
    "relative_path": string;
    "format": string;
    "content"?: ContentRefDTO | null;
}

/**
 * ResolutionDTO 是单个冲突选择。
 */
export interface ResolutionDTO {
    "resource_id": string;
    "choice": string;
}

/**
 * ResolvePlanDTO 是 ResolvePlan 输入。
 */
export interface ResolvePlanDTO {
    "plan_id": string;
    "resolutions": ResolutionDTO[] | null;
}

/**
 * ResolveRestorePlanDTO 是回滚决议输入（ADR-0006 §3：无冲突决议面）。
 */
export interface ResolveRestorePlanDTO {
    "plan_id": string;

    /**
     * exact|allow_partial（沿 P2 枚举；空值缺省 allow_partial）
     */
    "requested_exactness": string;

    /**
     * 逐资源 skip 决议，固化于 resolved plan
     */
    "skip_resource_ids": string[] | null;
}

/**
 * RestoreBlockedItemDTO 是 exact 阻塞清单行（draft 时点 exact_infeasible 证据，
 * ADR-0006 §4）。
 */
export interface RestoreBlockedItemDTO {
    "resource_id": string;
    "relative_path": string;
    "marker": string;
}

/**
 * RestorePlanDTO 是回滚计划投影（Status 沿 sync_plans CHECK 读取时投影；
 * ExactFeasible 为实时就绪面，非 draft 静态标记）。
 */
export interface RestorePlanDTO {
    "schema_version": number;
    "plan_id": string;
    "relation_id": string;
    "target_commit_id": string;

    /**
     * draft|resolved|confirmed|applied|expired|stale
     */
    "status": string;
    "exact_feasible": boolean;
    "blocked_by": RestoreBlockedItemDTO[] | null;
    "items": RestorePlanItemDTO[] | null;

    /**
     * resolved 后回填 exact|allow_partial
     */
    "requested_exactness"?: string;

    /**
     * 恒非空（restore_acknowledge）
     */
    "confirmation_requirements": ConfirmationRequirementDTO[] | null;
    "expires_at": string;
    "created_at": string;
}

/**
 * RestorePlanItemDTO 是回滚计划单资源行。Marker 枚举
 * restorable_from_cas|redownload_required|user_object_required|unrecoverable
 * （delete 行不占四标记）；MarkerReason 仅 user_object_required 行
 * （no_redownload_info|cf_unavailable|hash_format_unsupported）；Skipped/Staged
 * 为读取时实时投影；Availability 仅 redownload_required 行（ok|unknown）；
 * ExpectedDigest 仅 user_object_required 行（验收入库的目标摘要）。
 */
export interface RestorePlanItemDTO {
    "resource_id": string;
    "relative_path": string;

    /**
     * create|modify|delete
     */
    "change_kind": string;

    /**
     * delete 行为空串
     */
    "marker": string;
    "marker_reason"?: string;
    "skipped": boolean;
    "staged": boolean;

    /**
     * 手放 mod 删除＝「不可重取」警示（ADR-0006 §5）
     */
    "deletion_warn"?: boolean;

    /**
     * 「旧版本不留存」警示位（判定归票 #64）
     */
    "preserve_skip"?: boolean;

    /**
     * ok|unknown，仅 redownload_required 行
     */
    "availability"?: string;

    /**
     * 仅 ok 行；仅提示，版本决策归 packwiz
     */
    "newer_available"?: boolean;

    /**
     * user_object_required 行验收入库目标摘要
     */
    "expected_digest"?: string;
}

/**
 * RestorePrepareDTO 是准备回滚输入（Q4：目标 baseline 后端由 commit 推导，
 * 不收 baseline id）。
 */
export interface RestorePrepareDTO {
    "relation_id": string;

    /**
     * 任意历史提交（含 restore 提交=重做）；head 合法（空差异计划）
     */
    "commit_id": string;
}

/**
 * RetentionSettingsDTO 是保留策略设置投影（config.toml [retention] 承载，
 * ADR-0007 §2/§7/§8；K=3 硬保底固定不可调，不设键）。
 */
export interface RetentionSettingsDTO {
    "schema_version": number;

    /**
     * 默认 20，范围 5–200
     */
    "keep_commits": number;

    /**
     * 默认 90，范围 7–365
     */
    "keep_days": number;

    /**
     * 默认 1 GiB，范围 128 MiB–20 GiB
     */
    "relation_capacity_bytes": number;

    /**
     * 默认 32 MiB，范围 1 MiB–512 MiB；0＝不限
     */
    "preserve_max_bytes": number;

    /**
     * 默认 7，范围 1–90
     */
    "trash_days": number;
}

/**
 * RuntimeCandidateDTO 是运行实例发现候选（registered 按 adapter identity 幂等判定）。
 */
export interface RuntimeCandidateDTO {
    "instance_id": string;
    "instance_dir": string;
    "display_name": string;
    "game_dir": string;
    "minecraft"?: string;
    "modloader"?: string;
    "registered": boolean;
    "endpoint_id"?: string;
}

/**
 * SnapshotSummaryDTO 是快照摘要。
 */
export interface SnapshotSummaryDTO {
    "snapshot_id": string;
    "side": string;
    "captured_at": string;
    "snapshot_digest": string;
    "resource_count": number;
}

/**
 * StageUserObjectDTO 是用户对象补全输入：读字节→按 expected_digest 校验→暂存
 * （暂存路径不透出，契约 06 §3.5）。
 */
export interface StageUserObjectDTO {
    "plan_id": string;
    "resource_id": string;

    /**
     * 本地绝对路径
     */
    "source_path": string;
}

/**
 * SyncPlanDTO 是计划投影（Status 反映读取时计算的 stale/expired）。
 */
export interface SyncPlanDTO {
    "schema_version": number;
    "plan_id": string;
    "relation_id": string;
    "kind": string;
    "resolved_from_plan_id"?: string;
    "base_baseline_id"?: string;
    "base_baseline_digest"?: string;
    "input_project_snapshot_id": string;
    "input_runtime_snapshot_id": string;
    "input_project_snapshot_digest": string;
    "input_runtime_snapshot_digest": string;
    "relation_revision": number;
    "policy_digest": string;
    "expected_bindings": { [_ in string]?: string } | null;

    /**
     * RequestedExactness 是请求确切度 exact|allow_partial（契约 03 §2.6；
     * 与 Plan 模型 / sync_plans 列三处一致，ResolvePlan 继承）。
     */
    "requested_exactness": string;
    "plan_digest": string;
    "status": string;
    "expires_at": string;
    "operations": OperationDTO[] | null;
    "conflicts": ConflictDTO[] | null;
    "resolutions": ResolutionDTO[] | null;
    "confirmation_requirements": ConfirmationRequirementDTO[] | null;
    "summary": PlanSummaryDTO;
    "diagnostics": DiagnosticDTO[] | null;
}

/**
 * TaskDTO 是任务投影。
 */
export interface TaskDTO {
    "schema_version": number;
    "task_id": string;
    "relation_id"?: string;
    "task_sequence": number;
    "kind": string;
    "status": string;
    "outcome"?: string;
    "phase": string;
    "completed": number;
    "total": number;
    "message_key": string;
    "message_args": string[] | null;
    "plan_id"?: string;
    "commit_id"?: string;
    "can_cancel": boolean;
    "created_at": string;
    "updated_at": string;
    "problem"?: ProblemDTO | null;
}

/**
 * TaskPageDTO 是任务分页。
 */
export interface TaskPageDTO {
    "schema_version": number;
    "items": TaskDTO[] | null;
    "next_cursor"?: string;
}

/**
 * UpdateMappingPolicyDTO 是映射策略写输入（契约 03 §2.3；票 #20）：rules 整体
 * 替换，策略集身份保持不变；乐观锁——expected_revision 必须等于当前关系修订
 * （PolicyDTO.relation_revision 的读值），不等返回 err.mapping.stale_revision。
 */
export interface UpdateMappingPolicyDTO {
    "relation_id": string;
    "expected_revision": number;
    "rules": MappingRuleDTO[] | null;
}

/**
 * UpdateRetentionSettingsDTO 是保留设置写输入：五键整体替换（设置页表单全量
 * 提交）。单键范围校验，越界 → err.settings.retention_invalid（{0}=字段名），
 * 整体拒绝（不落任何键）。
 */
export interface UpdateRetentionSettingsDTO {
    "keep_commits": number;
    "keep_days": number;
    "relation_capacity_bytes": number;
    "preserve_max_bytes": number;
    "trash_days": number;
}

/**
 * WorkspaceDTO 是工作区详情。
 */
export interface WorkspaceDTO {
    "schema_version": number;
    "relation": RelationDTO;
    "state": WorkspaceStateDTO;
    "features": WorkspaceFeaturesDTO;
    "availability": ActionAvailabilityDTO[] | null;
    "latest_project_snapshot"?: SnapshotSummaryDTO | null;
    "latest_runtime_snapshot"?: SnapshotSummaryDTO | null;

    /**
     * AuthorizedApply 是工作区授权开关投影（relations.authorized_apply，schema v6；
     * 契约 06 §3.6：只增不删，票 #57）。
     */
    "authorized_apply": boolean;
}

/**
 * WorkspaceFeaturesDTO 表达当前版本/平台实现的能力（契约 03 §2.1；架构 §10.4）。
 * feature=false 的动作不注册：不出现在 availability 中，前端不渲染入口。
 */
export interface WorkspaceFeaturesDTO {
    "scan": boolean;
    "sync_preview": boolean;
    "sync_apply": boolean;
    "conflict_inspection": boolean;

    /**
     * none|choose_side|merge
     */
    "conflict_resolution": string;
    "history_view": boolean;
    "restore_preview": boolean;
    "restore_apply": boolean;

    /**
     * P1 恒 []；Phase 2 起为 ["copy"]
     */
    "materialization_modes": string[] | null;
}

/**
 * WorkspacePageDTO 是工作区分页。
 */
export interface WorkspacePageDTO {
    "schema_version": number;
    "items": WorkspaceDTO[] | null;
    "next_cursor"?: string;
}

/**
 * WorkspaceStateDTO 是工作区正交状态（架构 §10.5）。
 */
export interface WorkspaceStateDTO {
    "scan_state": string;
    "baseline_state": string;
    "diff_state": string;
    "relation_health": string;
    "active_task_id"?: string;
    "relation_revision": number;
}
