// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService 是项目源端点用例的 Wails 出口（契约 03 §1/§2.5；/sources 页）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DiscoverProjects 在 parentDir 内有限深度发现 Packwiz 项目源。
 */
export function DiscoverProjects(parentDir: string): $CancellablePromise<$models.ProjectCandidateDTO[] | null> {
    return $Call.ByID(1184568818, parentDir);
}

/**
 * GetProjectHealth 返回项目源端点健康（只读）。
 */
export function GetProjectHealth(endpointID: string): $CancellablePromise<$models.EndpointHealthDTO> {
    return $Call.ByID(2091353252, endpointID);
}

/**
 * ListProjects 返回全部已登记项目源。
 */
export function ListProjects(): $CancellablePromise<$models.EndpointDTO[] | null> {
    return $Call.ByID(202644305);
}

/**
 * RegisterProject 幂等登记项目源端点（fingerprint 身份，稳定 opaque ID）。
 */
export function RegisterProject(input: $models.RegisterEndpointDTO): $CancellablePromise<$models.EndpointDTO> {
    return $Call.ByID(1742234759, input);
}
