// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RuntimeService 是运行实例端点用例的 Wails 出口（契约 03 §1/§2.5；/runtimes 页）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DiscoverRuntimes 从 Prism 实例目录枚举运行实例候选。
 */
export function DiscoverRuntimes(): $CancellablePromise<$models.RuntimeCandidateDTO[] | null> {
    return $Call.ByID(3682225216);
}

/**
 * GetRuntimeHealth 返回运行实例端点健康（只读）。
 */
export function GetRuntimeHealth(endpointID: string): $CancellablePromise<$models.EndpointHealthDTO> {
    return $Call.ByID(1132189116, endpointID);
}

/**
 * ListRuntimes 返回全部已登记运行实例。
 */
export function ListRuntimes(): $CancellablePromise<$models.EndpointDTO[] | null> {
    return $Call.ByID(2626753431);
}

/**
 * RegisterRuntime 幂等登记运行实例端点（adapter identity 身份，稳定 opaque ID）。
 */
export function RegisterRuntime(input: $models.RegisterEndpointDTO): $CancellablePromise<$models.EndpointDTO> {
    return $Call.ByID(4287574629, input);
}
