// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 是设置/开关域用例的 Wails 出口（契约 06 §2/§3.6；票 #57）。
 * 与 SyncService 分立注册：保留设置（config.toml [retention] 承载）与工作区
 * 授权开关不与同步执行混装（契约 06 §2 服务归属 Q1/Q3）。回滚/下载/GC 等
 * 后续域能力另票点亮，本服务只承载三方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRetentionSettings 返回保留策略设置（未配置键归一为默认值；ADR-0007 §8）。
 */
export function GetRetentionSettings(): $CancellablePromise<$models.RetentionSettingsDTO> {
    return $Call.ByID(2036752898);
}

/**
 * SetWorkspaceAuthorized 切换工作区授权开关（relations.authorized_apply，schema v6）
 * 并返回更新后的 WorkspaceDTO（投影一致，契约 06 §3.6）。恢复期开关值保留，
 * 入口由既有 err.recovery.in_progress 门禁挡。
 */
export function SetWorkspaceAuthorized(relationID: string, enabled: boolean): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(2521588149, relationID, enabled);
}

/**
 * UpdateRetentionSettings 整体替换保留策略设置：单键范围校验，越界 →
 * err.settings.retention_invalid（{0}=字段名），整体拒绝（契约 06 §3.6）。
 * 返回写入后的设置投影。
 */
export function UpdateRetentionSettings(input: $models.UpdateRetentionSettingsDTO): $CancellablePromise<$models.RetentionSettingsDTO> {
    return $Call.ByID(3522339587, input);
}
