// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 是设置/开关域用例的 Wails 出口（契约 06 §2/§3.6；票 #57）。
 * 与 SyncService 分立注册：保留设置（config.toml [retention] 承载）与工作区
 * 授权开关不与同步执行混装（契约 06 §2 服务归属 Q1/Q3）。票 #65 起增载
 * RequestGC（设置页「立即回收空间」，消费票 #64 GC 任务面）——契约 06 §2
 * 注明的「3 方法」增为 4（偏差注记见 RequestGC）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetRetentionSettings 返回保留策略设置（未配置键归一为默认值；ADR-0007 §8）。
 */
export function GetRetentionSettings(): $CancellablePromise<$models.RetentionSettingsDTO> {
    return $Call.ByID(2036752898);
}

/**
 * RequestGC 建「立即回收空间」的 GC 任务（契约 06 §9，票 #65；消费票 #64 的
 * GC 任务面）：全局单飞，已有活跃（queued/running）gc 任务时幂等返回既有任务；
 * 安全窗口未开任务停 pending 排队（msg.task.gc.waiting 文案在任务中心可见，
 * 开窗自动续排同一任务跑完），不拒绝。任务进度/终态由既有任务投影自动覆盖。
 * 偏差注记：契约 06 §2 的「SettingsService 3 方法」因本方法增为 4——票 #64
 * 报告已明确 RequestGC 的 transport 归属移交本票，规格计数未及回改。
 */
export function RequestGC(): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(3618891204);
}

/**
 * SetWorkspaceAuthorized 切换工作区授权开关（relations.authorized_apply，schema v6）
 * 并返回更新后的 WorkspaceDTO（投影一致，契约 06 §3.6）。恢复期开关值保留，
 * 入口由既有 err.recovery.in_progress 门禁挡。
 */
export function SetWorkspaceAuthorized(relationID: string, enabled: boolean): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(2521588149, relationID, enabled);
}

/**
 * UpdateRetentionSettings 整体替换保留策略设置：单键范围校验，越界 →
 * err.settings.retention_invalid（{0}=字段名），整体拒绝（契约 06 §3.6）。
 * 返回写入后的设置投影。
 */
export function UpdateRetentionSettings(input: $models.UpdateRetentionSettingsDTO): $CancellablePromise<$models.RetentionSettingsDTO> {
    return $Call.ByID(3522339587, input);
}
