// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService 是新架构 P1 只读核心的 Wails 出口（与 legacy 三服务并存注册）。
 * 不暴露 Apply/ConfirmPlan/Restore（Phase 2/3 能力，未实现即不出现在产品操作面）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTask 取消任务。
 */
export function CancelTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2403637576, taskID);
}

/**
 * CreateRelation 消费预检并创建 Relation。
 */
export function CreateRelation(preparationID: string): $CancellablePromise<$models.RelationDTO> {
    return $Call.ByID(1642239991, preparationID);
}

/**
 * GetPlan 查询计划（stale/expired 为读取时投影）。
 */
export function GetPlan(planID: string): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(1492305782, planID);
}

/**
 * GetTask 查询任务。
 */
export function GetTask(taskID: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(3191717288, taskID);
}

/**
 * GetWorkspace 返回工作区详情。
 */
export function GetWorkspace(relationID: string): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(2546983834, relationID);
}

/**
 * ListTasks 查询任务列表。
 */
export function ListTasks(relationID: string, active: boolean, cursor: string, limit: number): $CancellablePromise<$models.TaskPageDTO> {
    return $Call.ByID(1174647703, relationID, active, cursor, limit);
}

/**
 * ListWorkspaces 分页返回工作区。
 */
export function ListWorkspaces(cursor: string, limit: number): $CancellablePromise<$models.WorkspacePageDTO> {
    return $Call.ByID(181626509, cursor, limit);
}

/**
 * PrepareRelation 执行端点登记预检。
 */
export function PrepareRelation(input: $models.PrepareRelationDTO): $CancellablePromise<$models.RelationPreparationDTO> {
    return $Call.ByID(246549514, input);
}

/**
 * PrepareSync 生成不可变 draft plan。
 */
export function PrepareSync(input: $models.PrepareSyncDTO): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(1825923937, input);
}

/**
 * ResolvePlan 将冲突选择固化为新 resolved plan。
 */
export function ResolvePlan(input: $models.ResolvePlanDTO): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(3652495030, input);
}

/**
 * StartScan 启动（或复用）扫描任务。
 */
export function StartScan(relationID: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(507785416, relationID);
}
