// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService 是新架构 P1 只读核心的 Wails 出口（与 legacy 三服务并存注册）。
 * 不暴露 Apply/ConfirmPlan/Restore（Phase 2/3 能力，未实现即不出现在产品操作面）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyRebind 消费重绑预检并原位更新端点绑定（ADR-0003 单事务；恒 reinitialize）。
 */
export function ApplyRebind(preparationID: string): $CancellablePromise<$models.RelationDTO> {
    return $Call.ByID(2617810235, preparationID);
}

/**
 * CancelTask 取消任务。
 */
export function CancelTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2403637576, taskID);
}

/**
 * ConfirmPlan 确认 resolved 计划并创建 Apply 任务（契约 05 §3.1）。
 * 幂等重入（D4）返回既有任务；任务此刻无 runner（T04），保持 queued。
 */
export function ConfirmPlan(input: $models.ConfirmPlanDTO): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(2865490822, input);
}

/**
 * CreateRelation 消费预检并创建 Relation。
 */
export function CreateRelation(preparationID: string): $CancellablePromise<$models.RelationDTO> {
    return $Call.ByID(1642239991, preparationID);
}

/**
 * GetChanges 资源级变更查询（契约 03 §2.2；票 #19：读时计算三方 Diff，
 * summary 全量计数不受筛选影响，items 按 resource_id 字节序分页）。
 */
export function GetChanges(input: $models.GetChangesDTO): $CancellablePromise<$models.ChangesPageDTO> {
    return $Call.ByID(492725454, input);
}

/**
 * GetHashCacheStats 返回 hash cache 命中统计（进程生命周期累计；
 * 热扫描命中证明与 T14 性能基线供数口）。
 */
export function GetHashCacheStats(): $CancellablePromise<$models.HashCacheStatsDTO> {
    return $Call.ByID(4242908060);
}

/**
 * GetMappingPolicy 读取关系的当前映射策略（契约 03 §2.3；票 #20）。
 */
export function GetMappingPolicy(relationID: string): $CancellablePromise<$models.PolicyDTO> {
    return $Call.ByID(2710272195, relationID);
}

/**
 * GetPlan 查询计划（stale/expired 为读取时投影）。
 */
export function GetPlan(planID: string): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(1492305782, planID);
}

/**
 * GetSnapshotDiagnostics 返回快照持久化的诊断列表（diag.mapping.collision、
 * diag.scan.* 等；票 #17：mapping_collision 等诊断在快照中可查）。
 */
export function GetSnapshotDiagnostics(relationID: string, snapshotID: string): $CancellablePromise<$models.DiagnosticDTO[] | null> {
    return $Call.ByID(1990565243, relationID, snapshotID);
}

/**
 * GetTask 查询任务。
 */
export function GetTask(taskID: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(3191717288, taskID);
}

/**
 * GetWorkspace 返回工作区详情。
 */
export function GetWorkspace(relationID: string): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(2546983834, relationID);
}

/**
 * ListPolicySuggestions 返回建议（默认不激活）的受管范围候选规则，
 * 供 /workspaces/new 页勾选后并入初始 policy（/workspaces/new 建议流）。
 */
export function ListPolicySuggestions(): $CancellablePromise<$models.MappingRuleDTO[] | null> {
    return $Call.ByID(870394590);
}

/**
 * ListTasks 查询任务列表。
 */
export function ListTasks(relationID: string, active: boolean, cursor: string, limit: number): $CancellablePromise<$models.TaskPageDTO> {
    return $Call.ByID(1174647703, relationID, active, cursor, limit);
}

/**
 * ListWorkspaces 分页返回工作区。
 */
export function ListWorkspaces(cursor: string, limit: number): $CancellablePromise<$models.WorkspacePageDTO> {
    return $Call.ByID(181626509, cursor, limit);
}

/**
 * PrepareRebind 执行重绑预检（契约 03 §2.4；票 #22）。
 */
export function PrepareRebind(input: $models.PrepareRebindDTO): $CancellablePromise<$models.RebindPreparationDTO> {
    return $Call.ByID(3483894384, input);
}

/**
 * PrepareRelation 执行端点登记预检。
 */
export function PrepareRelation(input: $models.PrepareRelationDTO): $CancellablePromise<$models.RelationPreparationDTO> {
    return $Call.ByID(246549514, input);
}

/**
 * PrepareSync 生成不可变 draft plan。
 */
export function PrepareSync(input: $models.PrepareSyncDTO): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(1825923937, input);
}

/**
 * ResolvePlan 将冲突选择固化为新 resolved plan。
 */
export function ResolvePlan(input: $models.ResolvePlanDTO): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(3652495030, input);
}

/**
 * StartScan 启动（或复用）扫描任务。
 */
export function StartScan(relationID: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(507785416, relationID);
}

/**
 * UpdateMappingPolicy 保存映射策略修改：编译校验 + 乐观锁 + 修订号同事务递增
 * （契约 03 §2.3；票 #20）。返回保存后的策略投影（含新关系修订）。
 */
export function UpdateMappingPolicy(input: $models.UpdateMappingPolicyDTO): $CancellablePromise<$models.PolicyDTO> {
    return $Call.ByID(1781301722, input);
}
