// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService 是 relation 域用例的 Wails 出口（与 legacy 三服务并存注册）。
 * 写路径（ConfirmPlan/Apply 执行/Restore）按 Phase 2 票面逐票点亮；读投影
 * （Apply 运行头/逐操作/历史提交）自票 #39 起挂载。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcknowledgeRecovery 人工确认恢复收口（契约 05 §3.4；票 #38）：前置
 * run=recovery_required（否则 err.recovery.not_required），效果 acknowledged_at
 * 落库 + 关系复位 healthy（头基线不动、不建 SyncCommit），发布
 * relation_invalidated 引导重扫；返回确认后的工作区投影。已确认重入幂等返回。
 */
export function AcknowledgeRecovery(taskID: string): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(2839175458, taskID);
}

/**
 * ApplyRebind 消费重绑预检并原位更新端点绑定（ADR-0003 单事务；恒 reinitialize）。
 */
export function ApplyRebind(preparationID: string): $CancellablePromise<$models.RelationDTO> {
    return $Call.ByID(2617810235, preparationID);
}

/**
 * CancelTask 取消任务。
 */
export function CancelTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2403637576, taskID);
}

/**
 * ConfirmPlan 确认 resolved 计划并创建 Apply 任务（契约 05 §3.1）。
 * 幂等重入（D4）返回既有任务；任务此刻无 runner（T04），保持 queued。
 */
export function ConfirmPlan(input: $models.ConfirmPlanDTO): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(2865490822, input);
}

/**
 * ConfirmRestorePlan 确认 resolved 回滚计划并创建 restore 任务（契约 06 §3.4；
 * 票 #60）：确认即建 tasks(kind=restore, queued) + apply_runs(prepared)，引擎
 * 协程接管执行（ApplyRestore 不上 wire，Q1）。幂等重入返回既有 TaskDTO；
 * failed 终局可重入建新运行；上一运行已 committed → err.plan.apply_not_reentrant。
 */
export function ConfirmRestorePlan(input: $models.ConfirmRestorePlanDTO): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(3356938010, input);
}

/**
 * CreateRelation 消费预检并创建 Relation。
 */
export function CreateRelation(preparationID: string): $CancellablePromise<$models.RelationDTO> {
    return $Call.ByID(1642239991, preparationID);
}

/**
 * GetApplyRun 返回该工作区当前/最近一次 Apply 运行头投影（契约 05 §3.2；票 #39）。
 * 关系无任何运行记录 → err.apply.no_run。
 */
export function GetApplyRun(relationID: string): $CancellablePromise<$models.ApplyRunDTO> {
    return $Call.ByID(3777018104, relationID);
}

/**
 * GetChanges 资源级变更查询（契约 03 §2.2；票 #19：读时计算三方 Diff，
 * summary 全量计数不受筛选影响，items 按 resource_id 字节序分页）。
 */
export function GetChanges(input: $models.GetChangesDTO): $CancellablePromise<$models.ChangesPageDTO> {
    return $Call.ByID(492725454, input);
}

/**
 * GetCommit 单提交详情，changes 全量（契约 05 §3.5；票 #39）；
 * 记录不存在或跨关系 → err.commit.not_found。
 */
export function GetCommit(relationID: string, commitID: string): $CancellablePromise<$models.CommitDTO> {
    return $Call.ByID(2632705040, relationID, commitID);
}

/**
 * GetHashCacheStats 返回 hash cache 命中统计（进程生命周期累计；
 * 热扫描命中证明与 T14 性能基线供数口）。
 */
export function GetHashCacheStats(): $CancellablePromise<$models.HashCacheStatsDTO> {
    return $Call.ByID(4242908060);
}

/**
 * GetMappingPolicy 读取关系的当前映射策略（契约 03 §2.3；票 #20）。
 */
export function GetMappingPolicy(relationID: string): $CancellablePromise<$models.PolicyDTO> {
    return $Call.ByID(2710272195, relationID);
}

/**
 * GetPlan 查询计划（stale/expired 为读取时投影）。
 */
export function GetPlan(planID: string): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(1492305782, planID);
}

/**
 * GetRestorePlan 查询回滚计划（对称 GetPlan 的读伴随，契约 06 §2；
 * stale/expired 为读取时投影）。
 */
export function GetRestorePlan(planID: string): $CancellablePromise<$models.RestorePlanDTO> {
    return $Call.ByID(2624076714, planID);
}

/**
 * GetSnapshotDiagnostics 返回快照持久化的诊断列表（diag.mapping.collision、
 * diag.scan.* 等；票 #17：mapping_collision 等诊断在快照中可查）。
 */
export function GetSnapshotDiagnostics(relationID: string, snapshotID: string): $CancellablePromise<$models.DiagnosticDTO[] | null> {
    return $Call.ByID(1990565243, relationID, snapshotID);
}

/**
 * GetTask 查询任务。
 */
export function GetTask(taskID: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(3191717288, taskID);
}

/**
 * GetWorkspace 返回工作区详情。
 */
export function GetWorkspace(relationID: string): $CancellablePromise<$models.WorkspaceDTO> {
    return $Call.ByID(2546983834, relationID);
}

/**
 * ListApplyOperations 逐操作清单分页（契约 05 §3.3；票 #39）：ordinal 升序，
 * cursor 为上一页末条 operation_id（GetChanges 同协议）；task 不存在或跨关系
 * → err.apply.run_not_found。DTO 为白名单投影，绝不含临时路径与 ownership proof
 * （契约 05 §0 硬约束 4）。
 */
export function ListApplyOperations(relationID: string, taskID: string, cursor: string, limit: number): $CancellablePromise<$models.ApplyOperationPageDTO> {
    return $Call.ByID(1119035195, relationID, taskID, cursor, limit);
}

/**
 * ListCommits 历史提交列表，created_at DESC 分页（契约 05 §3.5；票 #39）；
 * cursor 为上一页末条 commit_id。
 */
export function ListCommits(relationID: string, cursor: string, limit: number): $CancellablePromise<$models.CommitPageDTO> {
    return $Call.ByID(663465799, relationID, cursor, limit);
}

/**
 * ListPolicySuggestions 返回建议（默认不激活）的受管范围候选规则，
 * 供 /workspaces/new 页勾选后并入初始 policy（/workspaces/new 建议流）。
 */
export function ListPolicySuggestions(): $CancellablePromise<$models.MappingRuleDTO[] | null> {
    return $Call.ByID(870394590);
}

/**
 * ListTasks 查询任务列表。
 */
export function ListTasks(relationID: string, active: boolean, cursor: string, limit: number): $CancellablePromise<$models.TaskPageDTO> {
    return $Call.ByID(1174647703, relationID, active, cursor, limit);
}

/**
 * ListWorkspaces 分页返回工作区。
 */
export function ListWorkspaces(cursor: string, limit: number): $CancellablePromise<$models.WorkspacePageDTO> {
    return $Call.ByID(181626509, cursor, limit);
}

/**
 * PrepareRebind 执行重绑预检（契约 03 §2.4；票 #22）。
 */
export function PrepareRebind(input: $models.PrepareRebindDTO): $CancellablePromise<$models.RebindPreparationDTO> {
    return $Call.ByID(3483894384, input);
}

/**
 * PrepareRelation 执行端点登记预检。
 */
export function PrepareRelation(input: $models.PrepareRelationDTO): $CancellablePromise<$models.RelationPreparationDTO> {
    return $Call.ByID(246549514, input);
}

/**
 * PrepareRestore 准备回滚：只收 relation_id + commit_id，目标 baseline 后端推导；
 * 四标记判定 + CF 尽力探测，draft 落 sync_plans(kind=restore)（契约 06 §3.1）。
 * 成功 → RestorePlanDTO（status=draft）。
 */
export function PrepareRestore(input: $models.RestorePrepareDTO): $CancellablePromise<$models.RestorePlanDTO> {
    return $Call.ByID(3538135376, input);
}

/**
 * PrepareSync 生成不可变 draft plan。
 */
export function PrepareSync(input: $models.PrepareSyncDTO): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(1825923937, input);
}

/**
 * QuickUpdate 统一快速更新（契约 07 §2/§3.1，票 #86）：阻塞到链收口再返回
 * （对 wire 是一次 Promise），同步三态 no_diff|apply_started|awaiting_confirmation；
 * 链内失败 AppError 透传零新码。
 */
export function QuickUpdate(relationID: string): $CancellablePromise<$models.QuickUpdateResultDTO> {
    return $Call.ByID(3969617035, relationID);
}

/**
 * ResolvePlan 将冲突选择固化为新 resolved plan。
 */
export function ResolvePlan(input: $models.ResolvePlanDTO): $CancellablePromise<$models.SyncPlanDTO> {
    return $Call.ByID(3652495030, input);
}

/**
 * ResolveRestorePlan 固化回滚决议（契约 06 §3.3）：仅 partial 逐资源 skip，
 * exact 遇就绪面不满前置拒绝（err.restore.exact_infeasible）。
 */
export function ResolveRestorePlan(input: $models.ResolveRestorePlanDTO): $CancellablePromise<$models.RestorePlanDTO> {
    return $Call.ByID(3523848938, input);
}

/**
 * StageUserObject 用户对象补全（契约 06 §3.5）：draft/resolved 均可补全；
 * 按 expected_digest 验收不符 → err.userobject.hash_mismatch（{0}=期望摘要，
 * 可重试）。成功返回更新后的 RestorePlanDTO（该行 staged=true）。
 */
export function StageUserObject(input: $models.StageUserObjectDTO): $CancellablePromise<$models.RestorePlanDTO> {
    return $Call.ByID(3042442895, input);
}

/**
 * StartScan 启动（或复用）扫描任务。
 */
export function StartScan(relationID: string): $CancellablePromise<$models.TaskDTO> {
    return $Call.ByID(507785416, relationID);
}

/**
 * UpdateMappingPolicy 保存映射策略修改：编译校验 + 乐观锁 + 修订号同事务递增
 * （契约 03 §2.3；票 #20）。返回保存后的策略投影（含新关系修订）。
 */
export function UpdateMappingPolicy(input: $models.UpdateMappingPolicyDTO): $CancellablePromise<$models.PolicyDTO> {
    return $Call.ByID(1781301722, input);
}
