// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";

/**
 * EventEnvelope 是后端事件的统一信封。
 * StreamSequence 在单次应用事件流内单调递增，用于发现连接期间漏包；
 * 与 Task.Sequence（任务内序号）、Relation.Revision（关系修订号）不可混用。
 */
export interface EventEnvelope {
    "schema_version": number;

    /**
     * evt_ 前缀
     */
    "event_id": string;
    "event_type": string;
    "stream_sequence": number;
    "emitted_at": string;
    "relation_id"?: string;
    "task_id"?: string;
    "payload": json$0.RawMessage;
}
