package sqlite

// schema_v1 是 v1 全量 DDL（架构文档 §8.3 的生产化版本）。
//
// 建表顺序经过拓扑排序以避免前向引用：
// projects/runtimes → relations → observed_snapshots → resource_representations；
// sync_baselines → baseline_resources / sync_plans → conflicts；
// tasks → operation_journal；sync_commits → commit_changes；objects → object_refs。
//
// 偏离说明（与 §8.3 原文的差异）：relations.head_baseline_id / head_commit_id
// 不带 REFERENCES 子句，仅 TEXT NULL。原因：relations ↔ sync_baselines/sync_commits
// 存在循环引用，而 SQLite 不支持 ALTER TABLE ADD CONSTRAINT，建表期间关闭/延迟
// 外键又会让迁移自身的约束验证失效。P1 阶段这两个 head 列由 repository 层在
// 同一事务内校验（见架构文档 §8.3 末尾的 Repository 契约要求），其余 FK 照抄原文。
const schemaV1 = `
CREATE TABLE schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE projects (id TEXT PRIMARY KEY, adapter TEXT NOT NULL, display_name TEXT NOT NULL, root_path TEXT NOT NULL, binding_fingerprint TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(adapter, root_path));
CREATE TABLE runtimes (id TEXT PRIMARY KEY, adapter TEXT NOT NULL, display_name TEXT NOT NULL, root_path TEXT NOT NULL, adapter_identity TEXT NOT NULL, binding_fingerprint TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(adapter, adapter_identity));
CREATE TABLE relations (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), runtime_id TEXT NOT NULL REFERENCES runtimes(id), policy_set TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, health TEXT NOT NULL CHECK(health IN ('healthy','endpoint_missing','rebind_required','recovery_required')), head_baseline_id TEXT NULL, head_commit_id TEXT NULL, created_at TEXT NOT NULL, UNIQUE(project_id, runtime_id));
CREATE TABLE preparations (preparation_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, expires_at TEXT NOT NULL, consumed_at TEXT NULL, input_json TEXT NOT NULL, project_json TEXT NULL, runtime_json TEXT NULL, policy_json TEXT NOT NULL, checks_json TEXT NOT NULL);
CREATE TABLE mappings (relation_id TEXT PRIMARY KEY REFERENCES relations(id), policy_id TEXT NOT NULL, revision INTEGER NOT NULL, policy_json TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE observed_snapshots (id TEXT PRIMARY KEY, relation_id TEXT NOT NULL REFERENCES relations(id), side TEXT NOT NULL CHECK(side IN ('project','runtime')), binding_fingerprint TEXT NOT NULL, scanner_name TEXT NOT NULL, scanner_version TEXT NOT NULL, captured_at TEXT NOT NULL, snapshot_digest TEXT NOT NULL, normalization_version INTEGER NOT NULL, policy_digest TEXT NOT NULL, resource_count INTEGER NOT NULL, diagnostics_json TEXT NOT NULL);
CREATE INDEX idx_snapshots_latest ON observed_snapshots(relation_id, side, captured_at DESC);
CREATE TABLE resource_representations (snapshot_id TEXT NOT NULL REFERENCES observed_snapshots(id), resource_id TEXT NOT NULL, resource_kind TEXT NOT NULL, identity_provider TEXT NOT NULL, identity_key TEXT NOT NULL, identity_confidence TEXT NOT NULL, policy_id TEXT NOT NULL, relative_path TEXT NOT NULL, format TEXT NOT NULL, content_algorithm TEXT NULL, content_digest TEXT NULL, size INTEGER NULL, semantic_json TEXT NOT NULL, PRIMARY KEY(snapshot_id, resource_id));
CREATE TABLE sync_baselines (id TEXT PRIMARY KEY, relation_id TEXT NOT NULL REFERENCES relations(id), parent_id TEXT NULL REFERENCES sync_baselines(id), created_at TEXT NOT NULL, baseline_digest TEXT NOT NULL, normalization_version INTEGER NOT NULL);
CREATE TABLE baseline_resources (baseline_id TEXT NOT NULL REFERENCES sync_baselines(id), resource_id TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('present','absent')), logical_digest TEXT NOT NULL, project_representation_json TEXT NULL, runtime_representation_json TEXT NULL, recoverability TEXT NOT NULL, PRIMARY KEY(baseline_id, resource_id));
CREATE TABLE sync_plans (id TEXT PRIMARY KEY, relation_id TEXT NOT NULL REFERENCES relations(id), kind TEXT NOT NULL CHECK(kind IN ('initialize','sync','restore')), resolved_from_plan_id TEXT NULL REFERENCES sync_plans(id), base_baseline_id TEXT NULL REFERENCES sync_baselines(id), input_project_snapshot_id TEXT NOT NULL REFERENCES observed_snapshots(id), input_runtime_snapshot_id TEXT NOT NULL REFERENCES observed_snapshots(id), relation_revision INTEGER NOT NULL, plan_digest TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','resolved','confirmed','applied','expired','stale')), expires_at TEXT NOT NULL, normalization_version INTEGER NOT NULL, plan_json TEXT NOT NULL);
CREATE TABLE conflicts (plan_id TEXT NOT NULL REFERENCES sync_plans(id), resource_id TEXT NOT NULL, conflict_kind TEXT NOT NULL, detail TEXT NULL, PRIMARY KEY(plan_id, resource_id));
CREATE TABLE tasks (id TEXT PRIMARY KEY, relation_id TEXT NULL REFERENCES relations(id), kind TEXT NOT NULL CHECK(kind IN ('scan','apply','restore','gc')), status TEXT NOT NULL CHECK(status IN ('queued','running','succeeded','failed','cancelled','recovery_required')), phase TEXT NOT NULL, sequence INTEGER NOT NULL DEFAULT 0, outcome TEXT NULL CHECK(outcome IN ('exact','partial')), can_cancel INTEGER NOT NULL DEFAULT 0, completed INTEGER NOT NULL DEFAULT 0, total INTEGER NOT NULL DEFAULT 0, message_key TEXT NOT NULL DEFAULT '', message_args_json TEXT NOT NULL DEFAULT '[]', plan_id TEXT NULL, commit_id TEXT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, problem_json TEXT NULL);
CREATE INDEX idx_tasks_relation ON tasks(relation_id, status, created_at DESC);
CREATE TABLE task_events (event_id TEXT PRIMARY KEY, stream_sequence INTEGER NOT NULL UNIQUE, event_type TEXT NOT NULL CHECK(event_type IN ('task_updated','relation_invalidated','watch_failed')), emitted_at TEXT NOT NULL, relation_id TEXT NULL, task_id TEXT NULL, payload_json TEXT NOT NULL);
CREATE TABLE hash_cache (root_fingerprint TEXT NOT NULL, relative_path TEXT NOT NULL, size_bytes INTEGER NOT NULL, mtime_unix_nano INTEGER NOT NULL, file_key TEXT NOT NULL DEFAULT '', algorithm TEXT NOT NULL, digest TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(root_fingerprint, relative_path, size_bytes, mtime_unix_nano, file_key));
CREATE TABLE operation_journal (task_id TEXT NOT NULL REFERENCES tasks(id), operation_id TEXT NOT NULL, ordinal INTEGER NOT NULL, status TEXT NOT NULL, target_relative_path TEXT NOT NULL, before_digest TEXT NULL, after_digest TEXT NULL, temp_relative_path TEXT NULL, recovery_ref_json TEXT NULL, ownership_proof_json TEXT NOT NULL, operation_json TEXT NOT NULL, result_json TEXT NULL, PRIMARY KEY(task_id, operation_id), UNIQUE(task_id, ordinal));
CREATE TABLE sync_commits (id TEXT PRIMARY KEY, relation_id TEXT NOT NULL REFERENCES relations(id), parent_id TEXT NULL REFERENCES sync_commits(id), created_at TEXT NOT NULL, plan_id TEXT NOT NULL REFERENCES sync_plans(id), verified_project_snapshot_id TEXT NOT NULL REFERENCES observed_snapshots(id), verified_runtime_snapshot_id TEXT NOT NULL REFERENCES observed_snapshots(id), previous_baseline_id TEXT NULL REFERENCES sync_baselines(id), result_baseline_id TEXT NOT NULL REFERENCES sync_baselines(id), commit_kind TEXT NOT NULL CHECK(commit_kind IN ('initialize','sync','restore')), completeness TEXT NOT NULL CHECK(completeness IN ('exact','partial')), remaining_change_count INTEGER NOT NULL DEFAULT 0, summary_json TEXT NOT NULL);
CREATE TABLE commit_changes (commit_id TEXT NOT NULL REFERENCES sync_commits(id), resource_id TEXT NOT NULL, change_kind TEXT NOT NULL, project_before TEXT NULL, project_after TEXT NULL, runtime_before TEXT NULL, runtime_after TEXT NULL, PRIMARY KEY(commit_id, resource_id));
CREATE TABLE objects (algorithm TEXT NOT NULL, digest TEXT NOT NULL, size INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('staging','ready','quarantined')), created_at TEXT NOT NULL, PRIMARY KEY(algorithm, digest));
CREATE TABLE object_refs (owner_type TEXT NOT NULL, owner_id TEXT NOT NULL, algorithm TEXT NOT NULL, digest TEXT NOT NULL, purpose TEXT NOT NULL, size INTEGER NOT NULL, PRIMARY KEY(owner_type, owner_id, algorithm, digest, purpose), FOREIGN KEY(algorithm, digest) REFERENCES objects(algorithm, digest));
CREATE TABLE plan_confirmations (plan_id TEXT NOT NULL REFERENCES sync_plans(id), plan_digest TEXT NOT NULL, confirmation_token TEXT NOT NULL, relation_revision INTEGER NOT NULL, acknowledgements_json TEXT NOT NULL, confirmed_at TEXT NOT NULL, expires_at TEXT NOT NULL, PRIMARY KEY(plan_id, confirmation_token));
`
