// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModInfo 描述 packwiz 项目中的一个 mod（对应 index.toml 中 mods/ 条目指向的文件）
 */
export interface ModInfo {
    "id": string;
    "name": string;

    /**
     * client / server / both
     */
    "side": string;

    /**
     * 中文标签
     */
    "side_cn": string;

    /**
     * pw.toml 中的 version（不一定存在）
     */
    "version": string;

    /**
     * 下载文件名
     */
    "file": string;

    /**
     * pw.toml 完整路径
     */
    "path": string;

    /**
     * CurseForge 源信息（0 表示非 CurseForge 源）
     */
    "cf_project_id": number;
    "cf_file_id": number;

    /**
     * 本地缓存的 CurseForge 文件信息（获取后填充）
     * displayName（版本）
     */
    "cf_version": string;

    /**
     * 发布日期
     */
    "cf_file_date": string;

    /**
     * 1=正式版 2=测试版 3=Alpha
     */
    "cf_release_type": number;
}

/**
 * ModUpdateInfo 是 packwiz update 检查结果中单个 mod 的信息
 */
export interface ModUpdateInfo {
    "name": string;
    "has_update": boolean;
    "current_file": string;
    "latest_file": string;
    "error": string;
}

/**
 * ModVersionResult 是一次批量获取中单个 mod 的结果
 */
export interface ModVersionResult {
    "id": string;
    "name": string;

    /**
     * displayName
     */
    "version": string;
    "ok": boolean;
    "error": string;
}

/**
 * PackProject 描述一个已导入的 packwiz 项目
 */
export interface PackProject {
    "name": string;

    /**
     * pack.toml 所在目录
     */
    "path": string;

    /**
     * pack.toml 完整路径
     */
    "pack_toml": string;
    "version": string;
    "author": string;
    "pack_format": string;
    "minecraft": string;

    /**
     * fabric / forge / neoforge / quilt ...
     */
    "modloader": string;
    "modloader_version": string;
    "mods": ModInfo[] | null;

    /**
     * 解析失败时的原因
     */
    "error": string;
}

/**
 * RefreshResult 是 packwiz CLI 执行结果
 */
export interface RefreshResult {
    "ok": boolean;
    "output": string;
}

/**
 * ToolInfo 描述一个工具的检测结果
 */
export interface ToolInfo {
    /**
     * packwiz / prism-launcher
     */
    "name": string;

    /**
     * 是否已安装
     */
    "found": boolean;

    /**
     * 可执行文件或配置目录的完整路径
     */
    "path": string;

    /**
     * 发现来源: config / path / default-dir
     */
    "source": string;

    /**
     * 对用户的中文说明
     */
    "message": string;

    /**
     * 需要加入 PATH 的目录（无可加目录时为空）
     */
    "env_dir": string;

    /**
     * 该目录是否已在用户 PATH 中
     */
    "env_ok": boolean;
}

/**
 * UpdateCheckResult 是 packwiz update 检查结果
 */
export interface UpdateCheckResult {
    "ok": boolean;
    "output": string;

    /**
     * 有更新的 mod
     */
    "updates": ModUpdateInfo[] | null;

    /**
     * 检查失败 / 跳过 / 无更新源的 mod
     */
    "errors": ModUpdateInfo[] | null;
}
