// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PackwizService 负责 packwiz 项目的导入、解析与管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdates 通过 packwiz 官方 update 命令检查项目更新（不实际应用）：
 * 运行 `packwiz update --all` 并向确认提示喂入 "n"，使其打印更新列表后取消
 */
export function CheckUpdates(projectName: string): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(752923826, projectName);
}

/**
 * FetchAllModVersions 批量获取项目中所有 CurseForge 源 mod 的版本（并发上限 8），
 * 结果写入本地缓存并逐条返回
 */
export function FetchAllModVersions(projectName: string): $CancellablePromise<$models.ModVersionResult[] | null> {
    return $Call.ByID(3715337844, projectName);
}

/**
 * FetchModVersion 获取单个 mod 的 CurseForge 版本信息，写入本地缓存，
 * 返回带缓存字段的 ModInfo
 */
export function FetchModVersion(projectName: string, modID: string): $CancellablePromise<$models.ModInfo> {
    return $Call.ByID(980627508, projectName, modID);
}

/**
 * ImportProject 导入一个 pack.toml 并返回解析结果（同名项目会覆盖路径）
 */
export function ImportProject(packTomlPath: string): $CancellablePromise<$models.PackProject> {
    return $Call.ByID(2950539706, packTomlPath);
}

/**
 * ListProjects 返回所有已导入项目的解析结果
 */
export function ListProjects(): $CancellablePromise<$models.PackProject[] | null> {
    return $Call.ByID(2506904462);
}

/**
 * RefreshProject 在项目目录执行 `packwiz refresh` 并返回输出
 */
export function RefreshProject(name: string): $CancellablePromise<$models.RefreshResult> {
    return $Call.ByID(3050250452, name);
}

/**
 * RemoveProject 按名称移除项目，返回剩余项目列表
 */
export function RemoveProject(name: string): $CancellablePromise<$models.PackProject[] | null> {
    return $Call.ByID(4221499969, name);
}

/**
 * UpdateMods 应用更新：modName 非空时更新单个（packwiz update <name>，无确认直接应用），
 * 为空时更新全部（packwiz update --all -y）。
 * name 为 .pw.toml 文件名（即 mod id）
 */
export function UpdateMods(projectName: string, modName: string): $CancellablePromise<$models.RefreshResult> {
    return $Call.ByID(2687918632, projectName, modName);
}
