// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PackwizService 负责 packwiz 项目的导入、解析与管理
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ImportProject 导入一个 pack.toml 并返回解析结果（同名项目会覆盖路径）
 */
export function ImportProject(packTomlPath: string): $CancellablePromise<$models.PackProject> {
    return $Call.ByID(2950539706, packTomlPath);
}

/**
 * ListProjects 返回所有已导入项目的解析结果
 */
export function ListProjects(): $CancellablePromise<$models.PackProject[] | null> {
    return $Call.ByID(2506904462);
}

/**
 * RefreshProject 在项目目录执行 `packwiz refresh` 并返回输出
 */
export function RefreshProject(name: string): $CancellablePromise<$models.RefreshResult> {
    return $Call.ByID(3050250452, name);
}

/**
 * RemoveProject 按名称移除项目，返回剩余项目列表
 */
export function RemoveProject(name: string): $CancellablePromise<$models.PackProject[] | null> {
    return $Call.ByID(4221499969, name);
}
